### ISSUE TITLE
Convention in order to calculate Gab

### ISSUE THREAD

**Issue by lcrippa** [QcmPlab/CDMFT-LANC-ED#4]
Ciao,

stavo riguardando il codice e confrontandolo con la versione NONSU2 del single site. Mi sono accorto di una discrepanza che potrebbe avere alcune conseguenze:

la premessa è che questo codice calcola G1=<c†_a+c†_b | c_a+c_b>  e G2=<c†_a+ic†_b | c_a-ic_b> per le componenti offdiagonali. Se guardate a linea 96-98 di ED_GF_NORMAL.f90, la G off-diagonale è calcolata come 1/2(G1 -i*G2 -(1-i)G_aa -(1-i)G_bb). 

Questo si può verificare controllando per esempio il fatto che il peso a linea 809 e 890 è -xi*norm2, quindi sta effettivamente sottraendo G2.

Ora, se si fa il conto con questa convenzione, quello che vien fuori non è G_ab, ma G_ba, se non ho sbagliato i calcoli.
Infatti questa implementazione risale al vecchio codice single-site, prima che N_up N_dw fossero disaccoppiati (ca. 2017).
Nel repo edipack2.0, adesso, viene usata un'altra convenzione: G1 e G2 sono calcolate come prima, ma la G off-diagonale è calcolata come 1/2(G1 +i*G2 -(1+i)G_aa -(1+i)G_bb), e qui sono d'accordo che questo effettivamente dia G_ab.

Ora, questo nella maggior parte dei casi potrebbe non aver alcun risvolto, ma consideriamo per esempio il BHZ, componenti G_sito12_orb12 e G_sito21_orb21. Queste hanno, per esempio, la parte immaginaria opposta. Non è che questo ci porta a costruire una G, e di conseguenza una Σ, ribaltate?

In ogni caso, una soluzione a questo sarebbe di portare la G anche qui alla nuova convenzione, ossia xi * norm2 e G_ab= 1/2(G1 +i*G2 -(1+i)G_aa -(1+i)G_bb)

**Comment by lcrippa** [comment]
Update: ho discusso con Adriano ed in realtà potrebbe darsi che questa convenzione sia quella giusta. Infatti, dando un'occhiata alla discussione dopo eq.20 nel computer physics communications si nota che la formula per C_ab è relativa a quantità del tipo <c†|1/w-(H-E)|c>. In questa espressione c'è un problema, ossia, equivalentemente, c† e c sono scambiati *oppure* il segno al denominatore di (H-E) è sbagliato.

Questo vorrebbe dire che effettivamente con la "nuova convenzione" stiamo calcolando G_ba e non G_ab.
Di conseguenza, probabilmente sono giusti i conti CDMFT, mentre sono sbagliati i conti NONSU2.
Per sincerarcene sarebbe buono fare dei test: io sto guardando un modello t2g con U=0; Σ dovrebbe essere 0 a tappeto.

Apro una issue su EDIpack2

**Comment by beddalumia** [comment]
Ciao Lorenzo, grazie mille, ho letto anche di là. Mi sembra di capire che dopo il tuo test qui possiamo chiudere. Per NONSU2 scrivo di là tra un po', controllo un paio di cose.

**Comment by aamaricci** [comment]
Ciao a tutti,

io confermo che per il BHZ-Eccitonico TUTTE le componenti della Sigma sono
nulle (in 1d-12) con U=U'=U''=0 con l'attuale versione del codice.
Anche se un sollievo per i dati, temo un falso positivo come gia' discusso
con Lorenzo.
Immagino la cosa verra' anche per Gabriele.

Lorenzo se vuoi piu' tardi ci risentiamo cosi' implemento localmente il
debug che hai fatto in CDMFT anche per il caso nonSU2 e faccio un paio di
ulteriori tests.
Ora devo scappare a prendere figlio 2 a scuola.

A

**Comment by lcrippa** [comment]
Pare che con la modifica NONSU2 sia corretto. Probabilmente quindi va fixato. Controllate l'altro bug.

**Comment by beddalumia** [comment]
Per facilita' di consultazione in futuro lascio qua il link all'altra issue: https://github.com/aamaricci/EDIpack2.0/issues/6

**Comment by aamaricci** [comment]
Ottimo! Grande Gabriele bella idea.

A

Il giorno mer 22 mag 2024 alle 15:25 Gabriele Bellomia <
***@***.***> ha scritto:
